### ISSUE TITLE
Daffodil warnings excessive - suppress somehow

### ISSUE THREAD

**Issue by mbeckerle** [DFDLSchemas/NACHA#2]
When using this schema with Daffodil (2.1 branch), you get a lot of warnings like this:
```
Schema Definition Warning: Element has no empty representation so cannot have XSD default='0' as a default value.
Schema context: element reference {ach:2013}PriorityCode Location line 55 column 18 in file:/home/mbeckerle-unencrypted/DFDLSchemas/NACHA/2013/nacha_records.xsd
```
These should be suppressed somehow. Ideally suppressing only this warning.

**Comment by smhdfdl** [comment]
The warning is misleading, it should say that the default value can only be applied on unparsing (where the criteria is that the element is not in the infoset).

**Comment by mbeckerle** [comment]
Ok. I'll open a ticket to that effect on Daffodil.

**Comment by mbeckerle** [comment]
https://issues.apache.org/jira/browse/DAFFODIL-1874

**Comment by mbeckerle** [comment]
Fixed in Pull Request https://github.com/DFDLSchemas/NACHA/pull/3

However that will not be merged until the corresponding version of daffodil that supports this fix has been released.

**Comment by mbeckerle** [comment]
Fixed. Apache Daffodil (incubating) version 2.1.0 contains the fix, and that is now published. Regression test using TravisCI shows no flurry of warnings anymore.
